let arr = [
  {
    name:'HTML',
    list:[
      {
        title:'html事件',
        url:'http://www.w3school.com.cn/tags/html_ref_eventattributes.asp'
      },
      {
        title:'HTML/CSS/JS编码规范',
        url:'https://juejin.im/post/599ececb5188252423583c27'
      },
    ]
  },
  {
    name:'JS',
    list:[
      {
        title:'JavaScript数组的十八般武艺',
        url:'https://juejin.im/post/5b684ef9e51d451964629ba1'
      },
      {
        title:'js中的event详解',
        url:'https://blog.csdn.net/woxingx/article/details/54176320'
      },
      {
        title:'event(事件对象)详解',
        url:'https://www.cnblogs.com/websmile/p/8807334.html'
      },
      {
        title:'JavaScript中,{}+{}等于多少?',
        url:'http://www.cnblogs.com/ziyunfei/archive/2012/09/15/2685885.html'
      },
      {
        title:'JS高级技巧',
        url:'https://juejin.im/post/59ab7b36f265da24934b2470'
      },
      {
        title:'使用 JS 直接截取 视频片段 生成 gif 动画',
        url:'https://juejin.im/entry/5afce5c4f265da0b981ba7bf'
      },
      {
        title:'什么是跨域？',
        url:'https://segmentfault.com/a/1190000011145364'
      },
      
    ]
  },
  {
    name:'CSS',
    list:[
      {
        title:'Flex 布局教程：语法篇',
        url:'http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html'
      },
      {
        title:'解决flex新旧版本的兼容性写法',
        url:'https://blog.csdn.net/web_note/article/details/73527865'
      },
      {
        title:'CSS 变量教程',
        url:'https://juejin.im/post/5aebcb97f265da0ba56766d0'
      },
      {
        title:'CSS 查漏补缺',
        url:'https://juejin.im/entry/57b097a90a2b58006327430a'
      },
    ]
  },
  {
    name:'react',
    list:[
      {
        title:'react-router中文文档',
        url:'http://react-guide.github.io/react-router-cn/docs/Introduction.html'
      },
      {
        title:'Redux 中文文档',
        url:'http://www.redux.org.cn/'
      },
      {
        title:'setState方法的调用在React Component生命周期中表现',
        url:'https://www.acgsior.com/2017/12/18/react-setstate-in-component-lifecycle/'
      }
    ]
  },
  {
    name:'移动端',
    list:[
      {
        title:'ios和android 浏览器适配问题总结',
        url:'https://www.jianshu.com/p/31e53df2ecce'
      },
      {
        title:'移动端H5解惑-概念术语（一）',
        url:'https://juejin.im/post/5b6502686fb9a04fc34c2dfe'
      },
      {
        title:'移动端H5解惑-页面适配（二）',
        url:'https://juejin.im/post/5b6503dee51d45191e0d30d2'
      }
    ]
  },
  {
    name:'浏览器',
    list:[
      {
        title:'浅谈浏览器http的缓存机制',
        url:'http://www.cnblogs.com/vajoy/p/5341664.html'
      },
       {
        title:'浏览器同源政策及其规避方法',
        url:'http://www.ruanyifeng.com/blog/2016/04/same-origin-policy.html'
      },
       {
        title:'跨域资源共享 CORS 详解',
        url:'http://www.ruanyifeng.com/blog/2016/04/cors.html'
      },
       {
        title:'浏览器内核差异以及兼容性处理',
        url:'https://blog.csdn.net/Prince_fmx/article/details/78040416'
      }
    ]
  },
  {
    name:'前端资源',
    list:[
      {
        title:'JS进阶',
        url:'https://wtser.gitbooks.io/deep-learn-javascript/content/chapter1/README.html'
      },
      {
        title:'移动端调试痛点？——送你五款前端开发利器',
        url:'https://juejin.im/post/5b72e1f66fb9a009d018fb94'
      },
      {
        title:'github上最全的资源教程-前端涉及的所有知识体系',
        url:'https://blog.csdn.net/qq_34348873/article/details/52572008'
      },
      {
        title:'WEB前端要学些什么？WEB前端学习路线！WEB前端从入门到精通',
        url:'https://www.jianshu.com/p/ac8dd63b388e'
      },
      {
        title:'题目',
        url:'https://springhyc.github.io/InterviewLibrary/'
      },
      {
        title:'antd',
        url:'https://ant.design/index-cn'
      },
      {
        title:'antd-mobile',
        url:'https://mobile.ant.design/index-cn'
      },
      {
        title:'elementui',
        url:'http://element-cn.eleme.io/#/zh-CN/component/installation'
      },
      {
        title:'CountUp.js',
        url:'http://inorganik.github.io/countUp.js/'
      },
      {
        title:'gojs',
        url:'https://gojs.net/latest/index.html'
      },
      {
        title:'echarts',
        url:'http://echarts.baidu.com/'
      },
      {
        title:'Font Awesome',
        url:'https://fontawesome.com/'
      },
      {
        title:'iconfont',
        url:'http://www.iconfont.cn/'
      },
      {
        title:'caniuse',
        url:'https://www.caniuse.com/'
      },
      
    ]
  },
  {
    name:'JAVA',
    list:[
      {
        title:'JDK api',
        url:'http://tool.oschina.net/apidocs/apidoc?api=jdk-zh'
      },
      {
        title:'步骤二之创建接口：Intellij IDEA创建 java 后端 SpringBoot项目',
        url:'https://blog.csdn.net/u013777094/article/details/78580710/'
      },
      {
        title:'步骤三之连接数据库需要的第三方jar包本地引用：使用idea 在springboot添加本地jar包的方法',
        url:'https://blog.csdn.net/huxiaodong1994/article/details/80702278'
      }
    ]
  },
  {
    name:'npm',
    list:[
      {
        title:'通过npm发布自己的第一个React组件',
        url:'https://segmentfault.com/a/1190000012715027'
      },
      {
        title:'如何更新自己写的npm包（模块），假设已经在npm中发布了一个1.0.0版本的包',
        url:'https://blog.csdn.net/cvper/article/details/79051048'
      }
    ]
  },
  {
    name:'知识点',
    list:[
      {
        title:'HTML5的新特性概述（上）',
        url:'https://juejin.im/post/5be8d817e51d457f7a4aba13'
      },
      {
        title:'HTML5新特性概述(下)',
        url:'https://juejin.im/post/5bea349a518825170d1a9db1'
      },
      {
        title:'详解H5非常重要的28个新特性,新技巧和新技术',
        url:'http://www.php.cn/html5-tutorial-363047.html'
      },
      {
        title:'JavaScript 垃圾回收',
        url:'https://www.cnblogs.com/dolphinX/p/3348468.html'
      },
      {
        title:'个人总结（css3新特性）',
        url:'https://juejin.im/post/5a0c184c51882531926e4294'
      },
      {
        title:'前端面试之 CSS3 新特性',
        url:'https://juejin.im/entry/595f1e3c5188250d914dd53c'
      },
      {
        title:'一年半经验，百度、有赞、阿里面试总结',
        url:'https://juejin.im/post/5befeb5051882511a8527dbe'
      },
      {
        title:'前端面试的一道算法题（使用canvas解答图中图像个数以及面积大小）',
        url:'https://www.jianshu.com/p/f54d265f7aa4'
      },
    ]
  }
];
