let arr = [
  {
    name:'HTML',
    list:[
      {
        title:'html事件',
        url:'http://www.w3school.com.cn/tags/html_ref_eventattributes.asp'
      },
      {
        title:'222',
        url:'http://www.baidu.com'
      },
    ]
  },
  {
    name:'JS',
    list:[
      {
        title:'js中的event详解',
        url:'https://blog.csdn.net/woxingx/article/details/54176320'
      },
      {
        title:'event(事件对象)详解',
        url:'https://www.cnblogs.com/websmile/p/8807334.html'
      },
      {
        title:'JavaScript中,{}+{}等于多少?',
        url:'http://www.cnblogs.com/ziyunfei/archive/2012/09/15/2685885.html'
      }
    ]
  },
  {
    name:'CSS',
    list:[
      {
        title:'Flex 布局教程：语法篇',
        url:'http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html'
      },
      {
        title:'解决flex新旧版本的兼容性写法',
        url:'https://blog.csdn.net/web_note/article/details/73527865'
      },
      {
        title:'我们都一样',
        url:'http://www.baidu.com'
      },
    ]
  },
  {
    name:'react',
    list:[
      {
        title:'react-router中文文档',
        url:'http://react-guide.github.io/react-router-cn/docs/Introduction.html'
      },
      {
        title:'Redux 中文文档',
        url:'http://www.redux.org.cn/'
      },
      {
        title:'setState方法的调用在React Component生命周期中表现',
        url:'https://www.acgsior.com/2017/12/18/react-setstate-in-component-lifecycle/'
      }
    ]
  },
  {
    name:'移动端',
    list:[
      {
        title:'ios和android 浏览器适配问题总结',
        url:'https://www.jianshu.com/p/31e53df2ecce'
      },
      {
        title:'移动端H5解惑-概念术语（一）',
        url:'https://juejin.im/post/5b6502686fb9a04fc34c2dfe'
      },
      {
        title:'移动端H5解惑-页面适配（二）',
        url:'https://juejin.im/post/5b6503dee51d45191e0d30d2'
      }
    ]
  },
  {
    name:'浏览器',
    list:[
      {
        title:'浅谈浏览器http的缓存机制',
        url:'http://www.cnblogs.com/vajoy/p/5341664.html'
      },
       {
        title:'浏览器同源政策及其规避方法',
        url:'http://www.ruanyifeng.com/blog/2016/04/same-origin-policy.html'
      },
       {
        title:'跨域资源共享 CORS 详解',
        url:'http://www.ruanyifeng.com/blog/2016/04/cors.html'
      },
       {
        title:'浏览器内核差异以及兼容性处理',
        url:'https://blog.csdn.net/Prince_fmx/article/details/78040416'
      }
    ]
  },
  {
    name:'前端资源',
    list:[
      {
        title:'caniuse',
        url:'https://www.caniuse.com/'
      },
      {
        title:'github上最全的资源教程-前端涉及的所有知识体系',
        url:'https://blog.csdn.net/qq_34348873/article/details/52572008'
      },
      {
        title:'WEB前端要学些什么？WEB前端学习路线！WEB前端从入门到精通',
        url:'https://www.jianshu.com/p/ac8dd63b388e'
      },
      {
        title:'题目',
        url:'https://springhyc.github.io/InterviewLibrary/'
      }
    ]
  }
];
