let arr = [
  {
    name:'HTML',
    list:[
      {
        title:'html事件',
        url:'http://www.w3school.com.cn/tags/html_ref_eventattributes.asp'
      },
      {
        title:'HTML/CSS/JS编码规范',
        url:'https://juejin.im/post/599ececb5188252423583c27'
      },
      {
        title:'HTML5的新特性概述（上）',
        url:'https://juejin.im/post/5be8d817e51d457f7a4aba13'
      },
      {
        title:'HTML5新特性概述(下)',
        url:'https://juejin.im/post/5bea349a518825170d1a9db1'
      },
      {
        title:'详解H5非常重要的28个新特性,新技巧和新技术',
        url:'http://www.php.cn/html5-tutorial-363047.html'
      },
    ]
  },
  {
    name:'JS',
    list:[
      {
        title:'JavaScript数组的十八般武艺',
        url:'https://juejin.im/post/5b684ef9e51d451964629ba1'
      },
      {
        title:'js中的event详解',
        url:'https://blog.csdn.net/woxingx/article/details/54176320'
      },
      {
        title:'event(事件对象)详解',
        url:'https://www.cnblogs.com/websmile/p/8807334.html'
      },
      {
        title:'JavaScript中,{}+{}等于多少?',
        url:'http://www.cnblogs.com/ziyunfei/archive/2012/09/15/2685885.html'
      },
      {
        title:'JS高级技巧',
        url:'https://juejin.im/post/59ab7b36f265da24934b2470'
      },
      {
        title:'使用 JS 直接截取 视频片段 生成 gif 动画',
        url:'https://juejin.im/entry/5afce5c4f265da0b981ba7bf'
      },
      {
        title:'什么是跨域？',
        url:'https://segmentfault.com/a/1190000011145364'
      },
      {
        title:'为什么form表单提交没有跨域问题，但ajax提交有跨域问题？',
        url:'https://www.zhihu.com/question/31592553'
      },
      {
        title:'JavaScript 垃圾回收',
        url:'https://www.cnblogs.com/dolphinX/p/3348468.html'
      },
      {
        title:'深拷贝和浅拷贝',
        url:'https://juejin.im/post/5beb93de6fb9a049c30ac9ee'
      },
      {
        title:'前端实现文件的断点续传',
        url:'https://www.cnblogs.com/imwtr/p/5957391.html'
      },
      {
        title:'HTML5文件上传，断点续传的开发实现笔记',
        url:'https://blog.csdn.net/ababab12345/article/details/80581860'
      },
      {
        title:'ES6 Promise 和 Async/await的使用',
        url:'https://juejin.im/post/5a3c68426fb9a0451969c58e'
      },
      {
        title:'Async/Await替代Promise的6个理由',
        url:'https://juejin.im/post/58ede4c1b123db43cc365551'
      },
      {
        title:'如何中断一个正在发出的请求',
        url:'https://juejin.im/post/5acefbdbf265da237b227797'
      },
      {
        title:'观察者模式（ObserverPattern）',
        url:'https://juejin.im/post/57de12355bbb50005e648bd8'
      },
      {
        title:'设计模式之中介者模式',
        url:'https://juejin.im/post/5afbe3876fb9a07acc11e5c1'
      },
      {
        title:'浅析Service Worker',
        url:'https://juejin.im/post/5b5e8efbf265da0f60131ff4'
      },
      {
        title:'Service worker 介绍',
        url:'https://juejin.im/entry/59015d3c1b69e60058bb5cd9'
      },
      {
        title:'聊聊 webworker',
        url:'https://juejin.im/entry/591946e0da2f60005df4ce5b'
      },
      {
        title:'对webWorker多线程性能的初步探索',
        url:'https://juejin.im/post/5a02aacd51882531b15aec49'
      },
      {
        title:'WebSocket 浅析',
        url:'https://juejin.im/entry/58bd0579128fe1007e5c62c7'
      },
      {
        title:'WebSocket 与 TCP/IP',
        url:'https://juejin.im/entry/59228616da2f60005d5ab8e1'
      },
      {
        title:'WebWorker与WebSocket实现前端消息总线',
        url:'https://juejin.im/post/5b6d386ff265da0f9b4e1442'
      },
      {
        title:'翻译 | 原生 ECMAScript 模块：动态 import（）',
        url:'https://juejin.im/entry/58ba3308a22b9d005ede7565'
      },
      {
        title:'import、require、export、module.exports 混合使用详解',
        url:'https://juejin.im/post/5a2e5f0851882575d42f5609'
      },
      
    ]
  },
  {
    name:'CSS',
    list:[
      {
        title:'Flex 布局教程：语法篇',
        url:'http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html'
      },
      {
        title:'解决flex新旧版本的兼容性写法',
        url:'https://blog.csdn.net/web_note/article/details/73527865'
      },
      {
        title:'CSS 变量教程',
        url:'https://juejin.im/post/5aebcb97f265da0ba56766d0'
      },
      {
        title:'CSS 查漏补缺',
        url:'https://juejin.im/entry/57b097a90a2b58006327430a'
      },
      {
        title:'个人总结（css3新特性）',
        url:'https://juejin.im/post/5a0c184c51882531926e4294'
      },
      {
        title:'前端面试之 CSS3 新特性',
        url:'https://juejin.im/entry/595f1e3c5188250d914dd53c'
      },
      {
        title:'CSS 居中：完全指南',
        url:'https://juejin.im/entry/583b954b61ff4b006b55b43d'
      },
      {
        title:'position: sticky 详解（防坑指南）',
        url:'https://juejin.im/entry/5819999f67f356005879ffcf'
      },
      {
        title:'Tips-移动端滑动固顶效果(position: sticky)',
        url:'https://juejin.im/post/588f2fb2128fe1006c86dfd2'
      },
    ]
  },
  {
    name:'React',
    list:[
      {
        title:'react-router中文文档',
        url:'http://react-guide.github.io/react-router-cn/docs/Introduction.html'
      },
      {
        title:'Redux 中文文档',
        url:'http://www.redux.org.cn/'
      },
      {
        title:'setState方法的调用在React Component生命周期中表现',
        url:'https://www.acgsior.com/2017/12/18/react-setstate-in-component-lifecycle/'
      },
      {
        title:'react生命周期的基本用法',
        url:'https://www.jianshu.com/p/c9bc994933d5'
      },
      {
        title:'react-router入门和初步配置',
        url:'https://www.jianshu.com/p/d46ad14dab7c'
      },
      {
        title:'React-router4简约教程',
        url:'http://react-china.org/t/react-router4/15843'
      },
      {
        title:'react如何实现代码分割，路由动态加载',
        url:'https://blog.csdn.net/qq_35484341/article/details/80506297'
      },
      {
        title:'React router动态加载组件-适配器模式的应用',
        url:'http://www.cnblogs.com/walls/p/9632541.html'
      },
      {
        title:'深入理解 react-router 路由系统',
        url:'https://www.cnblogs.com/wyaocn/p/5805777.html'
      },
      {
        title:'React 数据流管理架构之 Redux',
        url:'https://juejin.im/entry/575578ad6be3ff006bfad8b9'
      },
      {
        title:'dva',
        url:'https://dvajs.com/guide/#%E7%89%B9%E6%80%A7'
      },
      {
        title:'redux中间件',
        url:'https://juejin.im/post/5ad83af26fb9a045e66c3d50'
      },
      {
        title:'React的基本知识和优缺点',
        url:'https://www.cnblogs.com/cxying93/p/6115425.html'
      },
      {
        title:'vue, react, angular优缺点',
        url:'https://blog.csdn.net/cherry_zhang18/article/details/78749329'
      },
      {
        title:'深入React知识点整理（一）',
        url:'https://segmentfault.com/a/1190000012432236'
      },
      {
        title:'深入React知识点整理（二）',
        url:'https://segmentfault.com/a/1190000012432321'
      },
    ]
  },
  {
    name:'Vue',
    list:[
      {
        title:'VUE 和 VUEX 中的数据流',
        url:'https://juejin.im/entry/58007bcf0bd1d00058eefe69'
      },
      {
        title:'深入理解 Vue 单向数据流',
        url:'https://juejin.im/entry/59e8b8a8518825579d131e51'
      },
    ]
  },
  {
    name:'移动端',
    list:[
      {
        title:'ios和android 浏览器适配问题总结',
        url:'https://www.jianshu.com/p/31e53df2ecce'
      },
      {
        title:'移动端H5解惑-概念术语（一）',
        url:'https://juejin.im/post/5b6502686fb9a04fc34c2dfe'
      },
      {
        title:'移动端H5解惑-页面适配（二）',
        url:'https://juejin.im/post/5b6503dee51d45191e0d30d2'
      },
      {
        title:'移动端适配问题解决方案',
        url:'https://juejin.im/post/5add7a44f265da0b886d05f8'
      },
      {
        title:'7 种方法解决移动端 Retina 屏幕 1px 边框问题',
        url:'https://juejin.im/entry/584e427361ff4b006cd22c7c'
      },
    ]
  },
  {
    name:'浏览器',
    list:[
      {
        title:'浅谈浏览器http的缓存机制',
        url:'http://www.cnblogs.com/vajoy/p/5341664.html'
      },
       {
        title:'浏览器同源政策及其规避方法',
        url:'http://www.ruanyifeng.com/blog/2016/04/same-origin-policy.html'
      },
       {
        title:'跨域资源共享 CORS 详解',
        url:'http://www.ruanyifeng.com/blog/2016/04/cors.html'
      },
       {
        title:'浏览器内核差异以及兼容性处理',
        url:'https://blog.csdn.net/Prince_fmx/article/details/78040416'
      },
       {
        title:'我知道的HTTP请求',
        url:'https://juejin.im/post/5a757d2f5188254e5c6c404a'
      },
       {
        title:'http请求头与响应头的应用',
        url:'https://juejin.im/post/5b854ddef265da43635d9302'
      },
       {
        title:'8大前端安全问题（上）',
        url:'https://juejin.im/entry/59f999d25188254897330bbc'
      },
       {
        title:'8大前端安全问题（下） – ThoughtWorks洞见',
        url:'https://juejin.im/entry/59fc370b518825619a020b6c'
      },
       {
        title:'HTTP2 详解',
        url:'https://juejin.im/post/5b88a4f56fb9a01a0b31a67e'
      },
       {
        title:'JavaScript异步并发请求问题',
        url:'https://www.jianshu.com/p/f01cc25f7a07'
      },
       {
        title:'TCP连接复用（TCP Connection Reuse）',
        url:'http://blog.51cto.com/gaibianziji/1211940'
      },
       {
        title:'hey，你的Event Loop',
        url:'https://juejin.im/post/5b63b4cb6fb9a04fb4017f5a'
      },
       {
        title:'javascript 事件流',
        url:'https://juejin.im/entry/5826ba9d0ce4630056f85e07'
      },
       {
        title:'js中的事件委托或是事件代理详解',
        url:'https://www.cnblogs.com/liugang-vip/p/5616484.html'
      },
    ]
  },
  {
    name:'前端资源',
    list:[
      {
        title:'JS进阶',
        url:'https://wtser.gitbooks.io/deep-learn-javascript/content/chapter1/README.html'
      },
      {
        title:'移动端调试痛点？——送你五款前端开发利器',
        url:'https://juejin.im/post/5b72e1f66fb9a009d018fb94'
      },
      {
        title:'github上最全的资源教程-前端涉及的所有知识体系',
        url:'https://blog.csdn.net/qq_34348873/article/details/52572008'
      },
      {
        title:'WEB前端要学些什么？WEB前端学习路线！WEB前端从入门到精通',
        url:'https://www.jianshu.com/p/ac8dd63b388e'
      },
      {
        title:'题目',
        url:'https://springhyc.github.io/InterviewLibrary/'
      },
      {
        title:'antd',
        url:'https://ant.design/index-cn'
      },
      {
        title:'antd-mobile',
        url:'https://mobile.ant.design/index-cn'
      },
      {
        title:'elementui',
        url:'http://element-cn.eleme.io/#/zh-CN/component/installation'
      },
      {
        title:'CountUp.js',
        url:'http://inorganik.github.io/countUp.js/'
      },
      {
        title:'gojs',
        url:'https://gojs.net/latest/index.html'
      },
      {
        title:'echarts',
        url:'http://echarts.baidu.com/'
      },
      {
        title:'Font Awesome',
        url:'https://fontawesome.com/'
      },
      {
        title:'iconfont',
        url:'http://www.iconfont.cn/'
      },
      {
        title:'caniuse',
        url:'https://www.caniuse.com/'
      },
      
    ]
  },
  {
    name:'JAVA',
    list:[
      {
        title:'JDK api',
        url:'http://tool.oschina.net/apidocs/apidoc?api=jdk-zh'
      },
      {
        title:'步骤二之创建接口：Intellij IDEA创建 java 后端 SpringBoot项目',
        url:'https://blog.csdn.net/u013777094/article/details/78580710/'
      },
      {
        title:'步骤三之连接数据库需要的第三方jar包本地引用：使用idea 在springboot添加本地jar包的方法',
        url:'https://blog.csdn.net/huxiaodong1994/article/details/80702278'
      }
    ]
  },
  {
    name:'npm',
    list:[
      {
        title:'通过npm发布自己的第一个React组件',
        url:'https://segmentfault.com/a/1190000012715027'
      },
      {
        title:'如何更新自己写的npm包（模块），假设已经在npm中发布了一个1.0.0版本的包',
        url:'https://blog.csdn.net/cvper/article/details/79051048'
      }
    ]
  },
  {
    name:'知识点',
    list:[
      {
        title:'一年半经验，百度、有赞、阿里面试总结',
        url:'https://juejin.im/post/5befeb5051882511a8527dbe'
      },
      {
        title:'前端面试的一道算法题（使用canvas解答图中图像个数以及面积大小）',
        url:'https://www.jianshu.com/p/f54d265f7aa4'
      },
      {
        title:'某大厂面试题与解析（欢迎纠错，优化）',
        url:'https://juejin.im/post/5be2fcd7f265da616d53aad0'
      },
      
      {
        title:'追求极致的用户体验ssr(基于vue的服务端渲染)',
        url:'https://www.cnblogs.com/jcscript/p/7574276.html'
      },
      {
        title:'入职第一天：前端leader手把手教我入门Vue服务器端渲染（SSR）',
        url:'https://www.imooc.com/article/28337'
      },
      {
        title:'从单页应用(SPA)到服务器渲染(SSR)',
        url:'https://www.jianshu.com/p/1e63f434051d'
      },
      
    ]
  }
];
